config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/articles/first", to: "articles#first_article"
  resources :articles do
    resources :comments
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image
  has_many_attached :pictures
  has_rich_text :body

  validates :title, presence: true
  validates :description, presence: true
  validates :image, presence: true

  def image_as_thumbnail
    image.variant(resize_to_limit: [300,300]).processed
  end
  def pictures_as_thumbnails
    pictures.map do |picture|
      picture.variant(resize_to_limit: [200,200]).processed
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params.require(:article).permit(:title, :description, :body, :image, pictures: []))
    @article.user_id = current_user.id
    if @article.save
      redirect_to @article, notice: "You have successfully created an article!"
    else
      render :new, alert: "There was an error while creating this article", status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :description, :body, :image, pictures: []))
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  def first_article
    @article_first = Article.first
  end

  def correct_user
    @article = current_user.articles.find_by(id: params[:id])
    redirect_to root_path, alert: "Not Authorized" if @article.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @articles = Article.all
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_form.html.erb
<div class="p-4">
  <%= form_with model: @article do |form| %>
    <div class="mb-4">
      <%= form.label :title, class: "block text-gray-700 font-bold mb-2"%>
      <%= form.text_field :title, class: "form-input w-full border rounded border-2 border-gray-500 bg-gray-200"%>
    </div>
    <div class="mb-4">
      <%= form.rich_text_area :body %>
    </div>
    <div class="mb-4">
      <%= form.label :description, class: "block text-gray-700 font-bold mb-2"%>
      <%= form.text_area :description, class: "form-textarea w-full border rounded border-2 border-gray-500 bg-gray-200", rows: 3 %>
    </div>
    <div class="mb-4">
      <%= form.label :image,  class: "block text-gray-700 font-bold mb-2" %>
      <%= form.file_field :image, class: "form-input w-full border rounded" %>
    </div>
    <div class="mb-4">
      <%= form.label :pictures,  class: "block text-gray-700 font-bold mb-2" %>
      <%= form.file_field :pictures, multiple: true, class: "form-input w-full border rounded" %>
    </div>
    <div>
      <%= form.submit class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"%>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="max-w-lg mt-4 mx-auto px-4 py-8 bg-gray-200 shadow-xl rounded-lg">
  <h1 class="text-2xl font-bold mb-4">Edit Article</h1>
  <%= render "/articles/form" %>
  <%= link_to "Back to home", root_path, class:"mx-4 text-blue-600 border text-md" %>
</div>

app/views/articles/first_article.html.erb
<div class="mx-5 my-4">
  <div>
    <h1 class="text-xl font-bold mb-2">
      <%= @article_first.title %>
    </h1>

    <p class="text-gray-700">
      <%= @article_first.description %>
    </p>
  </div>
</div>
<%= link_to "Back to home", root_path, class:"mx-5 my-4 text-blue-600 border text-md" %>

app/views/articles/index.html.erb
<table class="table-auto w-full border-4">
  <thead>
    <tr class="bg-blue-400 text-white">
      <th class="px-4 py-2 border">Article</th>
      <th class="px-4 py-2 border">Description</th>
      <th class="px-4 py-2 border">Actions</th>
    </tr>
  </thead>

  <tbody class="divide-y divide-gray-200">
    <% @articles.each do |article| %>
      <tr>
        <td class="px-4 py-2 text-center border text-blue-500">
          <%= link_to article.title, "/articles/#{article.id}"%>
        </td>
        <td class="px-4 py-2 text-center border">
          <%= truncate(article.description, length: 60) %>
        </td>
        <td class="px-4 py-2 text-center border">
          <% if article.user == current_user %>
            <%= link_to "Edit", "/articles/#{article.id}/edit", class: "text-green-500 hover:text-green-700 mr-2" %>
            <%= link_to "Delete", "/articles/#{article.id}", data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "text-red-500 hover:text-red-700" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<div class="max-w-lg mt-4 mx-auto px-4 py-8 bg-gray-200 shadow-xl rounded-lg">
  <h1 class="text-2xl font-bold mb-4">New Article</h1>
  <%= render "/articles/form" %>
  <%= link_to "Back to home", root_path, class:"mx-4 text-blue-600 border text-md" %>
</div>

app/views/articles/show.html.erb
<div class="flex justify-center items-center bg-gray-200">
  <div class="w-full max-w-2xl bg-white my-4 px-10 py-6 rounded-lg shadow-md">
    <div class="mb-4">
      <h1 class="text-xl font-bold mb-4 text-center">
        <%= @article.title %>
      </h1>

      <div class="flex mb-4">
        <% if @article.image.present? %>
          <div class="w-2/5 mr-4">
            <%= image_tag(@article.image_as_thumbnail, class: "block w-full h-full object-cover rounded") %>
          </div>
        <% end %>
        <div class="w-3/5">
          <%= @article.body %>
        </div>
      </div>
      
        <div class="swiper mySwiper mb-4">
          <div class="swiper-wrapper">
            <% @article.pictures.each do |picture| %>
              <div class="swiper-slide flex justify-center items-center text-center text-lg bg-white">
                <%= image_tag(picture, class: "block w-full h-full object-cover") %>
              </div>
            <% end %>
            
          </div>
          <div class="swiper-button-next"></div>
          <div class="swiper-button-prev"></div>
        </div>

      <p class="text-gray-700 my-2">
        <%= @article.description %>
      </p>
    </div>

    <div class="mb-4">
      <h2 class="text-xl font-bold">Comments:</h2>
      <%= render @article.comments %>
    </div>

    <div class="mb-4">
      <h2 class="text-xl font-bold mb-2">Add a Comment:</h2>
      <%= render 'comments/form' %>
    </div>

    <div class="text-center mt-6">
      <%= link_to "Back to home", root_path, class:"text-blue-600 border-b-2 border-transparent hover:border-blue-600" %>
    </div>
  </div>
</div>

<script>
  document.addEventListener("turbo:load", () => {
    var swiper = new Swiper(".mySwiper", {
      navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
      },
      loop: true,
    });
  });
</script>

app/views/comments/_comment.html.erb
<div>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
</div>

app/views/comments/_form.html.erb
<div>
  <%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
      <%= form.text_area :body, class: "form-textarea w-5% border rounded border-2 border-gray-500 bg-gray-200", rows: 2%>
    </p>
    <p>
      <%= form.submit class: "text-sm bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-2 rounded"%>
    </p>
  <% end %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArticlesApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
  </head>

  <body>
    <%= render 'pages/navbar'%>
    <% flash.each do |type,msg| %>
      <div id="flash-container" class="fixed top-0 w-full flex justify-center">
        <div id="flash" class="flash <%= type == 'alert' ? 'bg-red-600/75 px-2 py-2' : 'bg-green-600/75 px-2 py-2' %>">
          <%= msg %>
          <button id="closeFlash" class="ml-4 bg-transparent text-white font-bold py-2 px-4" onclick="closeMessage()">x</button>          
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

<script>
  const closeMessage = () => {
    const flashContainer = document.getElementById('flash-container');
    if (flashContainer) {
      flashContainer.style.display = 'none';
    }
  }
</script>

app/views/pages/_navbar.html.erb
<nav class="bg-gray-800 shadow-lg">
  <div class="max-w-7xl mx-auto px-4">
    <div class="flex justify-between h-16">
      <div class="flex items-center">
        <%= link_to "Articles App", root_path, class: "text-white text-lg font-bold" %>
      </div>
      <div class="flex items-center space-x-4">
        <div class="flex items-baseline space-x-4">
          <%= link_to "Articles Index", articles_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
          <%= link_to "First Article", article_path(id: "first"), class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
          <%= link_to "Create an Article", new_article_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
        </div>
          <div class="flex items-center space-x-4">
            <% if current_user %> 
              <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <% else %>
              <%= link_to "Get Started", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
              <%= link_to "Sign In", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %> 
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/pages/home.html.erb
<!--<div class="mt-6 ml-44 mr-80 px-8 py-8 bg-gradient-to-r from-sky-400 to-blue-700 shadow-2xl rounded-xl">
  <div class="mb-4">
    <%= link_to "Articles Index", "/articles", class: "text-red-600 hover:text-white text-2xl font-bold "%>
  </div>
  <div class="mb-4">
    <%= link_to "First Article", "/articles/first", class: "text-red-600 hover:text-white text-2xl font-bold" %>
  </div>
  <div class="mb-4">
    <% @articles.each do |article| %>      
      <div class="mb-4 flex items-center">
        <%= link_to "Show article #{article.id}", "/articles/#{article.id}", class: "text-white font-bold py-2 px-4 border-2 border-indigo-700 rounded mr-2 hover:bg-indigo-700" %>
        <% if article.user == current_user %>
          <%= link_to "Edit Article #{article.id}", "/articles/#{article.id}/edit", class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mr-2" %>
          <%= link_to "Delete Article #{article.id}", "/articles/#{article.id}", data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded mr-2"%>
        <% end %>
      </div> 
    <% end %>
  </div>

  <div class="mb-4">
    <%= link_to "Create an Article", "/articles/new", class: "text-red-600 hover:text-white text-2xl font-bold" %>
  </div>

  <div class="mb-4">
    <% if current_user %> 
      <%= link_to "Sign Out", destroy_user_session_path,  data: {turbo_method: :delete}, class: "bg-red-700 hover:bg-red-500 text-white font-bold py-2 px-4 rounded" %>
    <% else %>
      <%= link_to "Get Started", new_user_registration_path, class: "bg-violet-700 hover:bg-violet-500 text-white font-bold py-2 px-4 rounded mr-3" %>

      <%= link_to "Sign In", new_user_session_path, class: "bg-fuchsia-700 hover:bg-fuchsia-500 text-white font-bold py-2 px-4 rounded" %> <%# /users/sign_in %> 
    <% end %>
  </div>
</div>-->